GET http://localhost:3000/events HTTP/1.1
###
GET http://localhost:3000/admin HTTP/1.1
###
POST http://localhost:3000/new_event HTTP/1.1
###
DELETE http://localhost:3000/admin/:id HTTP/1.1
###
PUT http://localhost:3000/admin/:id HTTP/1.1
###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}
###
GET http://localhost:3000/check_login HTTP/1.1